window.RAW=[
"Ephemeral|/ɪˈfɛm.ər.əl/|a|Time|lasting a very short time|the ephemeral glow of dawn faded quickly|fleeting,brief",
"Serendipity|/ˌsɛr.ənˈdɪp..ti/|n|Fortune|finding good things by happy chance|our meeting was pure serendipity|luck,fortune",
"Eloquent|/ˈɛl.ə.kwənt/|a|Speech|fluent and persuasive in speaking|her eloquent plea moved the jury|articulate,fluent",
"Luminous|/ˈluː.mɪ.nəs/|a|Light|giving off light; bright|the luminous moon lit the path|radiant,glowing",
"Ubiquitous|/juːˈbɪk.wɪ.təs/|a|Presence|present everywhere|smartphones are ubiquitous today|omnipresent,common",
"Petrichor|/ˈpɛt.rɪ.kɔːr/|n|Nature|earthy smell after rain|the petrichor refreshed the dry town|scent,smell",
"Ineffable|/ɪnˈɛf.ə.bəl/|a|Emotion|too great for words|the ineffable calm of the lake|indescribable,unspeakable",
"Resilience|/rɪˈzɪl.i.əns/|n|Strength|recovering quickly from hardship|her resilience carried her through|toughness,grit",
"Ethereal|/ɪθɪə.ri.əl/|a|Beauty|delicate; otherworldly|the ethereal mist veiled the hills|heavenly,delicate",
"Halcyon|/ˈhæl.si.ən/|a|Time|happy and peaceful past|the halcyon days of youth|idyllic,golden",
"Melancholy|/ˈmɛl.ən.kɒl.i/|n|Emotion|deep lasting sadness|a quiet melancholy filled the room|sorrow,gloom",
"Wanderlust|/ˈwɒn.də.lʌst/|n|Motion|strong desire to travel|wanderlust pulled him abroad|restlessness,urge",
"Nostalgia|/nɒˈstæl.dʒə/|n|Emotion|longing for the past|the song filled her with nostalgia|longing,yearning",
"Euphoria|/juːˈfɔː.ri.ə/|n|Emotion|intense excitement and happiness|the win brought pure euphoria|bliss,elation",
"Solitude|/ˈsɒl..tjuːd/|n|State|peaceful being alone|he prized his morning solitude|seclusion,quiet",
"Sanguine|/ˈsæŋ.ɡwɪn/|a|Emotion|optimistic in difficulty|she stayed sanguine despite losses|hopeful,confident",
"Perspicacious|/ˌpɜː.spɪˈkeɪ.ʃəs/|a|Mind|shrewd and perceptive|a perspicacious judge of character|astute,shrewd",
"Redolent|/ˈrɛd.əl.ənt/|a|Sensation|fragrant; suggestive of|the hall was redolent of cedar|fragrant,aromatic",
"Verisimilitude|/ˌvɛr.ɪ.sɪˈmɪl.ɪ.tjuːd/|n|Truth|appearance of being true|the novel has striking verisimilitude|realism,plausibility",
"Languid|/ˈlæ.ɡwɪd/|a|Motion|slow and relaxed|a languid afternoon by the river|leisurely,unhurried",
"Aplomb|/əˈplɒm/|n|Strength|self-confidence under pressure|she answered with aplomb|poise,composure",
"Elysian|/ɪˈlɪʒ.ən/|a|Beauty|heavenly; blissful|an elysian garden in spring|paradisiacal,divine",
"Cacophony|/kəˈkɒf.ə.ni/|n|Sound|harsh mixture of sounds|the market was a cacophony of calls|discord,din",
"Quintessential|/ˌkwɪn.tˈsɛn.ʃəl/|a|Style|perfect example of a class|the quintessential gentleman|typical,classic",
"Sonder|/ˈsɒn.dər/|n|Mind|realizing each passerby has a rich life|crowds filled him with sonder|empathy,awareness",
"Aberration|/ˌæb.əˈreɪ.ʃən/|n|Truth|deviation from the normal|the warm day was an aberration|anomaly,deviation",
"Abjure|/əbˈdʒʊər/|v|Speech|renounce formally|he abjured his old habits|renounce,reject",
"Acrimony|/ˈæk.rɪ.mə.ni/|n|Social|bitterness of feeling|the divorce ended in acrimony|bitterness,hostility",
"Adroit|/əˈdrɔɪt/|a|Mind|clever and skillful|an adroit negotiator|skillful,deft",
"Alacrity|/əˈlæk.rɪ.ti/|n|Motion|brisk readiness|she accepted with alacrity|eagerness,speed",
"Altruism|/ˈæl.tru.ɪ.zəm/|n|Social|selfless concern for others|his altruism fed the hungry|selflessness,charity",
"Ambivalent|/æmˈbɪv.ə.lənt/|a|Emotion|having mixed feelings|she felt ambivalent about moving|unsure,torn",
"Anachronism|/əˈnæk.rə.nɪ.zəm/|n|Time|thing out of its time|the dial phone is an anachronism|relic,throwback",
"Anomaly|/əˈnɒm.ə.li/|n|Truth|something deviating from norm|the data anomaly puzzled scientists|oddity,exception",
"Antipathy|/ænˈtɪp.ə.θi/|n|Emotion|deep dislike|the two felt mutual antipathy|aversion,hostility",
"Apathy|/ˈæp.ə.θi/|n|Emotion|lack of interest|voter apathy lowered turnout|indifference,lethargy",
"Arbiter|/ˈɑː.bɪ.tər/|n|Social|one who judges|the arbiter of good taste|judge,authority",
"Arduous|/ˈɑː.dju.əs/|a|Strength|hard and tiring|the arduous climb tested them|grueling,hard",
"Ascetic|/əˈsɛt.ɪk/|a|Style|practicing severe self-denial|the ascetic monk owned little|austere,sparing",
"Assiduous|/əˈsɪd.ju.əs/|a|Craft|showing steady hard work|an assiduous researcher|diligent,careful",
"Audacious|/ɔːˈdeɪ.ʃəs/|a|Style|bold and daring|an audacious plan to climb|bold,daring",
"Auspicious|/ɔːˈspɪʃ.əs/|a|Fortune|favorable; promising|an auspicious start to the year|promising,favorable",
"Avarice|/ˈæv.ər.ɪs/|n|Emotion|extreme greed|avarice drove the miser|greed,covetousness",
"Banal|/bəˈnɑːl/|a|Style|boring and unoriginal|the banal remark added nothing|trite,dull",
"Benevolent|/bəˈnɛv.əl.ənt/|a|Social|kind and generous|a benevolent donor|kind,generous",
"Blithe|/blaɪð/|a|Emotion|lighthearted and casual|a blithe disregard for rules|carefree,light",
"Boisterous|/ˈbɔɪs.tər.əs/|a|Sound|noisy and energetic|the boisterous crowd cheered|rowdy,lively",
"Bolster|/ˈbəʊl.stər/|v|Strength|to support or strengthen|evidence bolstered her claim|support,boost",
"Bombastic|/bɒmˈbæs.tɪk/|a|Speech|high-sounding but empty|the bombastic speech bored us|pompous,grandiose",
"Buoyant|/ˈbɔɪ.ənt/|a|Emotion|cheerful and optimistic|a buoyant mood at the fair|cheerful,upbeat",
"Burgeon|/ˈbɜː.dʒən/|v|Nature|to grow rapidly|the burgeoning startup scene|flourish,expand",
"Cadence|/ˈkeɪ.dəns/|n|Sound|rhythmic flow of sound|the cadence of the rain|rhythm,beat",
"Cajole|/kəˈdʒəʊl/|v|Speech|coax with flattery|he cajoled her into singing|coax,wheedle",
"Candid|/ˈkæn.dɪd/|a|Speech|open and honest|a candid account of events|frank,honest",
"Capricious|/kəˈprɪʃ.əs/|a|Style|impulsive and unpredictable|the capricious weather ruined plans|fickle,volatile",
"Captivate|/ˈkæp.tɪ.veɪt/|v|Emotion|attract and hold interest|the story captivated the children|charm,enthrall",
"Catalyst|/ˈkæt.əl.ɪst/|n|Motion|a cause of change|the speech was a catalyst for reform|spark,stimulus",
"Caustic|/ˈkɔːs.tɪk/|a|Speech|sarcastic and biting|a caustic remark|biting,scathing",
"Celerity|/sɪˈlɛr.ɪ.ti/|n|Motion|swiftness of movement|the troops moved with celerity|speed,haste",
"Charisma|/kəˈrɪz.mə/|n|Social|compelling charm|the leader radiated charisma|charm,magnetism",
"Chicanery|/ʃˈkeɪ.nər.i/|n|Truth|deception by trickery|the deal reeked of chicanery|trickery,deceit",
"Clandestine|/klænˈdɛs.tɪn/|a|Style|kept secret|a clandestine meeting|secret,covert",
"Coalesce|/ˌkəʊ.əˈlɛs/|v|Motion|come together to form one|the groups coalesced into a party|merge,unite",
"Cogent|/ˈkəʊ.dʒənt/|a|Speech|clear and convincing|a cogent argument|convincing,compelling",
"Comely|/ˈkʌm.li/|a|Beauty|attractive in appearance|a comely young artist|pretty,handsome",
"Complacent|/kəmˈpleɪ.sənt/|a|Mind|smugly self-satisfied|do not grow complacent|smug,self-satisfied",
"Conundrum|/kəˈnʌn.drəm/|n|Mind|confusing difficult problem|the puzzle was a conundrum|riddle,puzzle",
"Convivial|/kənˈvɪv.i.əl/|a|Social|friendly and lively|a convivial dinner party|festive,sociable",
"Copious|/ˈkəʊ.pi.əs/|a|Style|abundant in supply|copious notes filled the desk|abundant,plentiful",
"Cursory|/ˈkɜː.sər.i/|a|Craft|hasty and without detail|a cursory glance at the report|brief,superficial",
"Dapper|/ˈdæp.ər/|a|Style|neat and stylish in dress|a dapper host|dashing,neat",
"Dauntless|/ˈdɔːnt.ləs/|a|Strength|fearless|a dauntless explorer|brave,bold",
"Deference|/ˈdɛf.ər.əns/|n|Social|respectful submission|she bowed in deference|respect,homage",
"Deft|/dɛft/|a|Craft|skillful and quick|a deft touch with the brush|skillful,adroit",
"Demure|/dɪˈmjʊər/|a|Style|quiet and modest|a demure smile|modest,reserved",
"Desolate|/ˈdɛs.əl.ət/|a|Place|empty and bleak|the desolate plain|bleak,barren",
"Dexterous|/ˈdɛk.stər.əs/|a|Craft|skillful with hands|a dexterous surgeon|agile,skillful",
"Didactic|/daɪˈdæk.tɪk/|a|Speech|intended to teach|a didactic fable|instructive,educational",
"Diligent|/ˈdɪl.ɪ.dʒənt/|a|Craft|hardworking|a diligent student|industrious,careful",
"Disparage|/dɪˈspær.ɪdʒ/|v|Speech|regard as worthless|do not disparage her work|belittle,devalue",
"Dissemble|/dɪˈsɛm.bəl/|v|Truth|conceal the truth|he dissembled his motives|pretend,mask",
"Dogmatic|/dɒɡˈmæt.ɪk/|a|Mind|asserting opinions as facts|a dogmatic tone|opinionated,rigid",
"Dour|/dʊər/|a|Emotion|stern and gloomy|a dour expression|gloomy,stern",
"Ebullient|/ɪˈbʌl.i.ənt/|a|Emotion|full of eager excitement|her ebullient laugh|exuberant,animated",
"Eclectic|/ɪˈklɛk.tk/|a|Style|drawing from many sources|an eclectic taste in music|diverse,varied",
"Edify|/ˈɛd.ɪ.faɪ/|v|Mind|instruct and improve|the lecture edified the crowd|enlighten,instruct",
"Efficacy|/ˈɛf.ɪ.kə.si/|n|Truth|power to produce results|the efficacy of the vaccine|effectiveness,potency",
"Effervescent|/ˌɛf.əˈvɛs.ənt/|a|Emotion|bubbly and vivacious|an effervescent performer|vivacious,bubbly",
"Egregious|/ɪˈɡriː.dʒəs/|a|Style|outstandingly bad|an egregious error|flagrant,glaring",
"Elegy|/ˈɛl.ɪ.dʒi/|n|Speech|poem of mourning|an elegy for the fallen|lament,requiem",
"Elucidate|/ɪˈluː.sɪ.deɪt/|v|Speech|make clear|please elucidate your point|clarify,explain",
"Enigma|/ɪˈnɪɡ.mə/|n|Mind|mysterious person or thing|the origin remains an enigma|mystery,puzzle",
"Ennui|/ɒnˈwiː/|n|Emotion|listless boredom|the ennui of long Sundays|boredom,tedium",
"Equanimity|/ˌɛk.wəˈnɪm.ɪ.ti/|n|Strength|calm composure|she faced it with equanimity|composure,calm",
"Erudite|/ˈɛr..daɪt/|a|Mind|having great knowledge|an erudite professor|learned,scholarly",
"Esoteric|/ˌɛs.əˈtɛr.ɪk/|a|Mind|understood by few|esoteric knowledge|obscure,arcane",
"Eulogy|/ˈjuː.lə.dʒi/|n|Speech|speech praising the dead|a moving eulogy|tribute,praise",
"Evanescent|/ˌɛv.əˈnɛs.ənt/|a|Time|quickly fading from sight|the evanescent rainbow|fading,fleeting",
"Exalt|/ɪɡˈzɔːlt/|v|Speech|praise highly|they exalted the hero|praise,glorify",
"Exemplary|/ɪɡˈzɛm.plər.i/|a|Style|serving as a model|exemplary conduct|model,ideal",
"Exhort|/ɪɡˈzɔːt/|v|Speech|strongly encourage|she exhorted the team|urge,encourage",
"Exonerate|/ɪɡˈzɒn.ə.reɪt/|v|Truth|absolve from blame|the report exonerated the officer|acquit,absolve",
"Expedient|/ɪkˈspiː.di.ənt/|a|Craft|convenient but perhaps improper|an expedient shortcut|practical,convenient",
"Exquisite|/ɪkˈskwɪz.ɪt/|a|Beauty|extremely beautiful|exquisite craftsmanship|beautiful,delicate",
"Extol|/ɪkˈstəʊl/|v|Speech|praise enthusiastically|critics extolled the film|praise,laud",
"Exuberant|/ɪɡˈzjuː.bər.ənt/|a|Emotion|full of energy|exuberant celebrations|ebullient,lively",
"Facetious|/fəˈsiː.ʃəs/|a|Speech|flippantly humorous|a facetious comment|flippant,joking",
"Fallible|/ˈfæl.ɪ.bəl/|a|Mind|capable of error|all humans are fallible|imperfect,weak",
"Fastidious|/fæˈstɪd.i.əs/|a|Craft|very attentive to detail|fastidious about grammar|meticulous,fussy",
"Fathom|/ˈfæð.əm/|v|Mind|understand deeply|I cannot fathom his choice|understand,grasp",
"Felicity|/fɪˈlɪs.ɪ.ti/|n|Emotion|intense happiness|the felicity of the moment|bliss,joy",
"Fervent|/ˈfɜː.vənt/|a|Emotion|intensely passionate|a fervent supporter|passionate,ardent",
"Fiasco|/fiˈæs.kəʊ/|n|Fortune|ridiculous failure|the event became a fiasco|debacle,failure",
"Flippant|/ˈflɪp.ənt/|a|Speech|not showing respect|a flippant answer|irreverent,cavalier",
"Flourish|/ˈflʌr.ɪʃ/|v|Nature|grow vigorously|the garden flourished|thrive,prosper",
"Foible|/ˈfɔɪ.bəl/|n|Mind|minor weakness|his charming foibles|fault,quirk",
"Foresight|/ˈfɔː.saɪt/|n|Mind|planning for the future|the foresight to save early|prudence,vision",
"Fortitude|/ˈfɔː.tɪ.tjuːd/|n|Strength|courage in pain|she bore it with fortitude|courage,stamina",
"Frugal|/ˈfruː.ɡəl/|a|Style|sparing and economical|a frugal meal|thrifty,sparing",
"Garrulous|/ˈɡær.ʊ.ləs/|a|Speech|excessively talkative|a garrulous taxi driver|chatty,loquacious",
"Gaunt|/ɡɔːnt/|a|Style|thin and bony|a gaunt face|haggard,thin",
"Germane|/dʒəˈmeɪn/|a|Mind|relevant to the subject|a germane observation|relevant,pertinent",
"Glib|/ɡlɪb/|a|Speech|fluent but insincere|a glib excuse|smooth,superficial",
"Gossamer|/ˈɡɒs.ə.mər/|a|Beauty|light and delicate|gossamer spider silk|delicate,fine",
"Gregarious|/ɡrɪˈɡɛə.ri.əs/|a|Social|fond of company|a gregarious host|sociable,outgoing"
];