window.RAW=(window.RAW||[]).concat([
"Guile|/ɡaɪl/|n|Mind|sly cunning|guile in negotiation|cunning,craftiness",
"Hackneyed|/ˈhæk.nid/|a|Style|unoriginal through overuse|a hackneyed plot|trite,clichéd",
"Harangue|/həˈræŋ/|n|Speech|lengthy scolding|a harangue about punctuality|tirade,lecture",
"Haphazard|/hæpˈhæz.əd/|a|Craft|lacking organization|a haphazard arrangement|random,chaotic",
"Hilarity|/hɪˈlær.ɪ.ti/|n|Emotion|amusement and laughter|the hilarity of the party|laughter,mirth",
"Humility|/hjuːˈmɪl..ti/|n|Social|modest view of oneself|she accepted praise with humility|modesty,meekness",
"Hyperbole|/haɪˈpɜː.bəl.i/|n|Speech|exaggerated statement|saying I waited forever is hyperbole|exaggeration,overstatement",
"Idyllic|/ɪˈdɪl.ɪk/|a|Place|happy and peaceful|an idyllic village|picturesque,peaceful",
"Immaculate|/ɪˈmæk.jʊ.lət/|a|Style|perfectly clean|an immaculate kitchen|spotless,pristine",
"Immutable|/ɪˈmjuː.tə.bəl/|a|Time|unchanging over time|the immutable laws of physics|fixed,unchanging",
"Impeccable|/ɪmˈpɛk.ə.bəl/|a|Craft|faultless|impeccable manners|flawless,perfect",
"Impervious|/ɪmˈpɜ.vi.əs/|a|Strength|not affected by|impervious to criticism|immune,resistant",
"Incisive|/ɪnˈsaɪ.sɪv/|a|Mind|sharply perceptive|an incisive analysis|penetrating,sharp",
"Incongruous|/ɪnˈkɒŋ.ɡru.əs/|a|Style|out of place|the tie was incongruous with the suit|inconsistent,jarring",
"Indolent|/ˈɪn.dəl.ənt/|a|Style|lazy|an indolent afternoon|lazy,idle",
"Indomitable|/ɪnˈdɒm..tə.bəl/|a|Strength|impossible to subdue|an indomitable spirit|unconquerable,resolute",
"Inexorable|/ɪnˈɛk.sər.ə.bəl/|a|Time|impossible to stop|the inexorable march of time|relentless,unstoppable",
"Ingenious|/ɪnˈdʒiː.ni.əs/|a|Mind|cleverly inventive|an ingenious device|inventive,clever",
"Inimitable|/ɪnˈɪm.ɪ.tə.bəl/|a|Style|too good to imitate|her inimitable style|unique,matchless",
"Insipid|/ɪnˈsɪp.d/|a|Style|lacking flavor or interest|an insipid soup|bland,dull",
"Intrepid|/ɪnˈtrɛp.ɪd/|a|Strength|fearless and adventurous|an intrepid reporter|brave,fearless",
"Irascible|/ɪˈræs.ɪ.bəl/|a|Emotion|easily angered|an irascible old man|irritable,cranky",
"Itinerant|/aɪˈtɪn.ər.ənt/|a|Motion|traveling from place to place|an itinerant musician|traveling,roving",
"Jaunty|/ˈdʒɔːn.ti/|a|Style|lively and cheerful|a jaunty hat|sprightly,cheerful",
"Jocular|/ˈdʒɒk.j.lər/|a|Speech|fond of joking|a jocular uncle|humorous,playful",
"Jovial|/ˈdʒəʊ.vi.əl/|a|Emotion|cheerful and friendly|a jovial host|jolly,merry",
"Jubilant|/ˈdʒuː.bɪ.lənt/|a|Emotion|triumphantly happy|the jubilant crowd|elated,triumphant",
"Judicious|/dʒuːˈdɪʃ.əs/|a|Mind|showing good judgment|a judicious use of funds|wise,sensible",
"Labyrinth|/ˈlæb.ə.rɪnθ/|n|Place|complicated maze|the old town is a labyrinth|maze,tangle",
"Laconic|/ləˈkɒn.ɪk/|a|Speech|using few words|a laconic reply|terse,concise",
"Lament|/ləˈmɛnt/|v|Emotion|mourn deeply|they lamented the loss|grieve,mourn",
"Laud|/lɔːd/|v|Speech|praise|critics lauded the actor|praise,extol",
"Legacy|/ˈlɛɡ.ə.si/|n|Time|something handed down|her legacy lives on|heritage,inheritance",
"Levity|/ˈlɛv.ɪ.ti/|n|Emotion|lightness and humor|a moment of levity|humor,lightness",
"Limpid|/ˈlɪm.pɪd/|a|Beauty|clear and transparent|limpid water|clear,transparent",
"Loquacious|/ləˈkweɪ.ʃəs/|a|Speech|very talkative|a loquacious guide|talkative,garrulous",
"Lustrous|/ˈlʌs.trəs/|a|Light|shining and glossy|lustrous hair|glossy,shining",
"Magnanimous|/mæɡˈnæn.ɪ.məs/|a|Social|generous and forgiving|a magnanimous victor|generous,noble",
"Malaise|/mæˈleɪz/|n|Emotion|general feeling of unease|a national malaise|unease,discomfort",
"Malleable|/ˈmæl.i.ə.bəl/|a|Style|easily shaped|the malleable clay|pliable,flexible",
"Meander|/miˈæn.dər/|v|Motion|wander aimlessly|the river meanders|wander,drift",
"Meticulous|/məˈtɪk.jʊ.ləs/|a|Craft|very careful and precise|meticulous records|careful,thorough",
"Mettle|/ˈmɛt.əl/|n|Strength|spirit and courage|the race tested their mettle|spirit,courage",
"Mirth|/mɜːθ/|n|Emotion|amusement and laughter|eyes full of mirth|laughter,glee",
"Momentum|/məˈmɛn.təm/|n|Motion|impetus gained by movement|the campaign gained momentum|impetus,drive",
"Monotonous|/məˈnɒt.ən.əs/|a|Sound|dull through sameness|a monotonous voice|tedious,repetitive",
"Mundane|/mʌnˈdeɪn/|a|Style|ordinary and boring|mundane chores|ordinary,banal",
"Nemesis|/ˈnɛm.ə.sɪs/|n|Social|longstanding rival|his old nemesis returned|rival,opponent",
"Nimble|/ˈnɪm.bəl/|a|Motion|quick and light in movement|nimble fingers|agile,quick",
"Nonchalant|/ˈnɒn.ʃəl.ənt/|a|Style|calm and unbothered|a nonchalant shrug|casual,cool",
"Notorious|/nəʊˈtɔ.ri.əs/|a|Social|famous for something bad|a notorious smuggler|infamous,disreputable",
"Nuance|/ˈnjuː.ɑns/|n|Mind|subtle difference|the nuances of meaning|subtlety,shade",
"Oblivion|/əˈblɪv.i.ən/|n|State|state of being forgotten|the band faded into oblivion|obscurity,forgetfulness",
"Obstinate|/ˈɒb.stɪ.nət/|a|Mind|stubborn|an obstinate child|stubborn,headstrong",
"Omen|/ˈəʊ.mɛn/|n|Fortune|sign of things to come|the dove was a good omen|sign,portent",
"Opulent|/ˈɒp.jʊ.lənt/|a|Style|rich and luxurious|an opulent palace|luxurious,wealthy",
"Oracle|/ˈɒr.ə.kəl/|n|Mind|source of wise advice|the oracle of the village|sage,prophet",
"Ostentatious|/ˌɒs.tnˈteɪ.ʃəs/|a|Style|showy and pretentious|an ostentatious car|showy,flashy",
"Outwit|/aʊtˈwɪt/|v|Mind|defeat by cleverness|she outwitted the trickster|outsmart,trick",
"Palatable|/ˈpæl.ə.tə.bəl/|a|Sensation|pleasant to taste|a palatable dish|tasty,agreeable",
"Pallid|/ˈpæl.ɪd/|a|Style|pale|a pallid complexion|pale,wan",
"Panacea|/ˌpæn.əˈsiː.ə/|n|Truth|cure-all|no panacea for all problems|cure-all,remedy",
"Paradox|/ˈpær.ə.dɒks/|n|Mind|seemingly contradictory statement|the paradox of choice|contradiction,puzzle",
"Paramount|/ˈpær.ə.maʊnt/|a|Style|more important than anything|safety is paramount|supreme,chief",
"Pensive|/ˈpɛn.sv/|a|Emotion|deeply thoughtful|a pensive mood|reflective,meditative",
"Perpetual|/pəˈpɛt.jʊ.əl/|a|Time|never ending|perpetual snow|endless,continuous",
"Pinnacle|/ˈpɪn.ə.kəl/|n|Place|highest point|the pinnacle of her career|summit,peak",
"Piquant|/ˈpiː.kənt/|a|Sensation|pleasantly sharp taste|a piquant sauce|spicy,tangy",
"Placid|/ˈplæs.ɪd/|a|Emotion|calm and peaceful|a placid lake|calm,tranquil",
"Ponder|/ˈpɒn.dər/|v|Mind|think carefully|she pondered the offer|consider,reflect",
"Pristine|/ˈprɪs.tiːn/|a|Style|in original condition|the pristine beach|unspoiled,pure",
"Profound|/prəˈfaʊnd/|a|Mind|very deep|a profound insight|deep,intense",
"Prolific|/prəˈlɪf.k/|a|Craft|producing much|a prolific writer|productive,fertile",
"Prudent|/ˈpruː.dənt/|a|Mind|acting with care|a prudent decision|wise,careful",
"Pungent|/ˈpʌŋ.dʒənt/|a|Sensation|strong sharp smell|a pungent cheese|sharp,acrid",
"Quaint|/kweɪnt/|a|Place|attractively unusual|a quaint cottage|charming,old-fashioned",
"Quench|/kwɛntʃ/|v|Motion|satisfy thirst|quench your thirst|satisfy,extinguish",
"Radiant|/ˈreɪ.di.ənt/|a|Light|sending out light|a radiant smile|glowing,bright",
"Rapture|/ˈræp.tʃər/|n|Emotion|great pleasure|she listened in rapture|ecstasy,delight",
"Reverie|/ˈrɛv.ər.i/|n|Mind|pleasant daydream|lost in a reverie|daydream,trance",
"Vigor|/ˈvɪɡ.ər/|n|Strength|physical strength and energy|the vigor of youth|energy,vitality",
"Vivid|/ˈvɪv.d/|a|Light|strong bright color|a vivid memory|bright,striking",
"Zeal|/ziːl/|n|Emotion|great enthusiasm|the zeal of a convert|passion,ardor",
"Zenith|/ˈzɛn.ɪθ/|n|Time|highest point in time|the zenith of the empire|peak,apex",
"Zest|/zɛst/|n|Emotion|eager enjoyment|a zest for life|enthusiasm,relish",
"Kindle|/ˈkɪn.dəl/|v|Motion|light a fire; arouse|kindle a flame of hope|ignite,arouse",
"Marvel|/ˈmɑː.vəl/|v|Emotion|be filled with wonder|we marveled at the view|wonder,admire",
"Haven|/ˈheɪ.vən/|n|Place|safe place|a haven from the storm|refuge,sanctuary",
"Chronicle|/ˈkrɒn.ɪ.kəl/|n|Time|record of events|a chronicle of the war|record,history",
"Beacon|/ˈbiː.kən/|n|Light|guiding light|a beacon of hope|signal,lighthouse",
"Bloom|/bluːm/|v|Nature|produce flowers|the roses bloomed|blossom,flower",
"Cascade|/kæˈskeɪd/|n|Nature|small waterfall|a cascade of water|waterfall,torrent",
"Dawn|/dɔːn/|n|Time|first light of day|the dawn broke softly|daybreak,sunrise",
"Dusk|/dʌsk/|n|Time|the darker part of evening|the dusk settled|twilight,sundown",
"Ember|/ˈɛm.bər/|n|Nature|glowing coal|the embers glowed|coal,spark",
"Gale|/ɡeɪl/|n|Nature|very strong wind|the gale shook the roof|wind,storm",
"Haze|/heɪz/|n|Nature|thin mist|a haze over the valley|mist,fog",
"Keen|/kiːn/|a|Mind|sharp and eager|a keen observer|sharp,eager",
"Lull|/lʌl/|n|Time|temporary calm|a lull in the storm|pause,break",
"Sage|/seɪdʒ/|n|Mind|wise person|the village sage|wise man,philosopher",
"Yonder|/ˈjɒn.dər/|r|Place|at a distance|the yonder hills|distant,far",
"Azure|/ˈæʒ.ər/|a|Light|bright blue like sky|the azure sky|blue,sky-blue",
"Brisk|/brɪsk/|a|Motion|quick and energetic|a brisk walk|quick,lively",
"Crisp|/krɪsp/|a|Sensation|firm and dry|the crisp autumn air|fresh,sharp",
"Dimple|/ˈdɪm.pəl/|n|Beauty|small hollow in cheek|a smile with dimples|hollow,indent",
"Elite|/eɪˈliːt/|n|Social|the best of a group|the elite of the field|best,cream",
"Fable|/ˈfeɪ.bəl/|n|Speech|short moral story|the fable of the tortoise|tale,story",
"Gleam|/ɡliːm/|n|Light|a faint light|a gleam of silver|glint,sparkle",
"Hush|/hʌʃ/|n|Sound|silence and quiet|a hush fell over the room|silence,quiet",
"Ivory|/ˈaɪ.vər.i/|n|Style|creamy white|an ivory gown|white,cream",
"Jolly|/ˈdʒɒl.i/|a|Emotion|happy and cheerful|a jolly song|merry,cheerful",
"Karma|/ˈkɑ.mə/|n|Fortune|actions shaping fate|karma caught up with him|fate,destiny",
"Lilt|/lɪlt/|n|Sound|pleasant rhythm in voice|a lilt in her voice|rhythm,bounce",
"Happiness|/ˈhæp.i.nəs/|n|Emotion|the state of being happy|her happiness lit the room|joy,delight",
"Sadness|/ˈsæd.nəs/|n|Emotion|the state of being sad|a quiet sadness in his eyes|sorrow,gloom",
"Joy|/dʒɔɪ/|n|Emotion|great pleasure and happiness|the joy of a reunion|elation,bliss",
"Sorrow|/ˈsɒr.əʊ/|n|Emotion|deep distress caused by loss|sorrow at the farewell|grief,sadness",
"Anger|/ˈæŋ.ɡər/|n|Emotion|strong feeling of displeasure|his anger faded by evening|fury,rage",
"Fear|/fɪər/|n|Emotion|unease caused by danger|fear of the dark|dread,fright",
"Hope|/həʊp/|n|Emotion|desire and expectation for good|hope for a better year|optimism,trust",
"Despair|/dɪˈspeər/|n|Emotion|complete loss of hope|moments of deep despair|hopelessness,gloom",
"Delight|/dɪˈlaɪt/|n|Emotion|great pleasure and joy|the children squealed with delight|pleasure,joy",
"Anxiety|/æŋˈzaɪ.ə.ti/|n|Emotion|worry and uneasy feelings|exam anxiety kept him awake|worry,unease",
"Serenity|/sɪˈrɛn.ɪ.ti/|n|Emotion|calm and peaceful state|the serenity of the lake|calm,peace",
"Grief|/ɡriːf/|n|Emotion|deep sorrow from loss|grief softened into memory|sorrow,heartache"
]);